-- 1. nominations (선곡회의 후보곡) 테이블 생성
CREATE TABLE IF NOT EXISTS public.nominations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gig_id bigint REFERENCES public.gigs(id) ON DELETE CASCADE NOT NULL,
    title text NOT NULL,
    artist text,
    required_parts text[] DEFAULT '{}'::text[],
    recommended_vocals jsonb DEFAULT '[]'::jsonb,
    sheet_exists boolean DEFAULT false,
    description text DEFAULT '',
    links jsonb DEFAULT '[]'::jsonb,
    created_by bigint REFERENCES public.performers(id) ON DELETE SET NULL,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_at timestamptz DEFAULT now() NOT NULL
);

COMMENT ON TABLE public.nominations IS '선곡회의 후보곡 및 추천곡 목록';
COMMENT ON COLUMN public.nominations.recommended_vocals IS '후보곡 추천 보컬 목록 ([{ id: number, name: string, generation?: number, part?: string }])';

-- 2. 기존 setlists에서 후보곡 데이터 이전
-- (후보곡 판별 조건: created_by가 있거나, required_parts가 있거나, session_members가 NULL인 곡)
INSERT INTO public.nominations (
    id,
    gig_id,
    title,
    artist,
    required_parts,
    recommended_vocals,
    sheet_exists,
    description,
    links,
    created_by,
    created_at,
    updated_at
)
SELECT
    id,
    gig_id,
    COALESCE(title, '제목 없음'),
    artist,
    COALESCE(required_parts, '{}'::text[]),
    COALESCE(recommended_vocals, '[]'::jsonb),
    COALESCE(sheet_exists, false),
    COALESCE(description, ''),
    COALESCE(links, '[]'::jsonb),
    created_by,
    created_at,
    COALESCE(updated_at, created_at)
FROM public.setlists
WHERE created_by IS NOT NULL 
   OR required_parts IS NOT NULL 
   OR session_members IS NULL;

-- 3. 이전된 후보곡들을 setlists 테이블에서 삭제
DELETE FROM public.setlists
WHERE id IN (SELECT id FROM public.nominations);

-- 4. nominations sequence 동기화
SELECT setval(
    pg_get_serial_sequence('public.nominations', 'id'),
    COALESCE((SELECT MAX(id) FROM public.nominations), 1),
    true
);

-- 5. nominations RLS 설정
ALTER TABLE public.nominations ENABLE ROW LEVEL SECURITY;

-- 5-1. SELECT 정책: 전체 공개
DROP POLICY IF EXISTS "Nominations select policy" ON public.nominations;
CREATE POLICY "Nominations select policy"
ON public.nominations FOR SELECT
USING (true);

-- 5-2. INSERT 정책: 공연 참여 부원 또는 관리자
DROP POLICY IF EXISTS "Nominations insert policy" ON public.nominations;
CREATE POLICY "Nominations insert policy"
ON public.nominations FOR INSERT
WITH CHECK (
    auth.role() = 'authenticated'
    AND (
        public.is_admin()
        OR EXISTS (
            SELECT 1 FROM public.performers
            WHERE performers.gig_id = nominations.gig_id
              AND performers.user_id = auth.uid()
              AND performers.id = nominations.created_by
        )
    )
);

-- 5-3. UPDATE 정책: 본인이 등록한 곡 또는 관리자
DROP POLICY IF EXISTS "Nominations update policy" ON public.nominations;
CREATE POLICY "Nominations update policy"
ON public.nominations FOR UPDATE
USING (
    public.is_admin()
    OR EXISTS (
        SELECT 1 FROM public.performers
        WHERE performers.id = nominations.created_by
          AND performers.user_id = auth.uid()
    )
)
WITH CHECK (
    public.is_admin()
    OR EXISTS (
        SELECT 1 FROM public.performers
        WHERE performers.id = nominations.created_by
          AND performers.user_id = auth.uid()
    )
);

-- 5-4. DELETE 정책: 본인이 등록한 곡 또는 관리자
DROP POLICY IF EXISTS "Nominations delete policy" ON public.nominations;
CREATE POLICY "Nominations delete policy"
ON public.nominations FOR DELETE
USING (
    public.is_admin()
    OR EXISTS (
        SELECT 1 FROM public.performers
        WHERE performers.id = nominations.created_by
          AND performers.user_id = auth.uid()
    )
);

-- 6. setlists RLS 정책 단순화 (오직 관리자만 관리, 일반 공개 조회)
DROP POLICY IF EXISTS "Setlists insert policy" ON public.setlists;
CREATE POLICY "Setlists insert policy"
ON public.setlists FOR INSERT
WITH CHECK (
    auth.role() = 'authenticated' AND public.is_admin()
);

DROP POLICY IF EXISTS "Setlists update policy" ON public.setlists;
CREATE POLICY "Setlists update policy"
ON public.setlists FOR UPDATE
USING (
    public.is_admin()
)
WITH CHECK (
    public.is_admin()
);

DROP POLICY IF EXISTS "Setlists delete policy" ON public.setlists;
CREATE POLICY "Setlists delete policy"
ON public.setlists FOR DELETE
USING (
    public.is_admin()
);
